Repository khawajaazfar2000/Hacktoberfest2022-Repository-2, pull requests merged in 2022-10, with the labels that each got.

#1 Switch first commit
  Switch.cpp
Labels: hackoctober, hacktober-accepted

#2 Queue ADDED
  Queue/Double ended Class/.vscode/tasks.json
  Queue/Double ended Class/Double_ended.cpp
  Queue/STL/.vscode/launch.json
  Queue/STL/.vscode/settings.json
  Queue/STL/.vscode/tasks.json
  Queue/STL/Double ended.cpp
Labels: hackoctober, hacktober-accepted

#3 Queue Doubt Solved
  Queue/Queue, Circular Queue, Queue using linkedlist.cpp
Labels: hackoctober, hacktober-accepted

#4 Python code ADDED
  Pyhton/dic.py
Labels: hackoctober, hacktober-accepted

#5 hacktoberfest 2022
  C++/caesar cipher.cpp
  Pyhton/caesar cipher.py
Labels: hackoctober, hacktober-accepted

#6 Create Biggest out of 3.cpp
  C++/Biggest out of 3.cpp
Labels: hackoctober, hacktober-accepted

#7 Create swap.cpp
  C++/swap.cpp
Labels: hackoctober, hacktober-accepted

#8 first commit
  Javascript/program2.js
Labels: hackoctober, hacktober-accepted

#9 Create BubbleSort.cpp
  C++/BubbleSort.cpp
Labels: hackoctober, hacktober-accepted

#10 Create knapsack_dp.cpp
  C++/knapsack_dp.cpp
Labels: hackoctober, hacktober-accepted

#15 Create Quiz.py
  Pyhton/Quiz.py
Labels: bug

#45 code add for Count Subsets With Equal Sum
  C++/count_subsets_with_equal_sum_dp.cpp
Labels: question

#46 Added GnomeSort.cpp
  GnomeSort.cpp
Labels: hackoctober, hacktober-accepted
